spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: '*'
            allowedOriginPatterns: '*'
            allowedMethods: '*'
            allowCredentials: true
      routes:
        - id: account
          uri: lb://account-service
          predicates:
            - Path=/api/account/**
        - id: userinfo
          uri: lb://account-service
          predicates:
            - Path=/api/user-info/**
        - id: forum
          uri: lb://forum-service
          predicates:
            - Path=/api/forum/**
  application:
    name: gateway
server:
  port: 10000
